[ASTL-260] Bug Fix - More explicit init/move operations that only breaks release build (#293)
## Description

Fixes an issue that only shows up with the release build and g++. The
reason why this wasn't revealed earlier is that release and g++ isn't
normally enabled in the integration flow matrix.

The error normally occurs when you try to run "just build release" on a
linux and g++ system. You'll get a very long error message that
contains:

```ASTL/src/impl/metric/scaling_formula.hpp:49:73: error: ‘*(astl::ScalingFormula*)((char*)&<unnamed> + offsetof(std::AnyFormula, std::variant<astl::IdentityFormula, astl::BitMaskFormula,
...
astl::ScalingFormula>::_M_u)).astl::ScalingFormula::_scale_factor’ may be used uninitialized [-Werror=maybe-uninitialized]
```

## Customer Impact

Bug fix for release build and improved initialization safety.

## Performance Impact

Negligible.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

CICD Must Pass

## Test Configuration

- OS name: Ubuntu
- OS version: 22.04, 24.04
- Compiler: g++

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my
feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream
modules
- [X] I have checked my code and corrected any misspellings

Ossmosis-Source-Commit: 4ba1cdf379eb8eb88f4abca717cd6a946c5d1453